version: '3'

services:
  nginx:
    restart: always
    image: nginx 
    container_name: nginx_server
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  db:
    image: postgres
    restart: always
    container_name: db_vacunas
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
  web:
    image: miguemat4/yo_vacuno:1.5
    restart: always
    build: ./
    container_name: vacunas
    volumes:
      - .:/src
      - /static:/static
    expose:
      - "8000"
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  database_data:
