# Generated by Django 2.2.5 on 2019-10-12 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.CharField(blank=True, max_length=25, null=True)),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')])),
                ('primer_nombre', models.CharField(max_length=255)),
                ('segundo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=255)),
                ('a_os', models.IntegerField(default=0)),
                ('meses', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.Comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('cui', models.CharField(max_length=255)),
                ('renglon', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(max_length=255)),
                ('choice', models.PositiveSmallIntegerField(choices=[(1, '< 1 año'), (2, '< 2 año'), (3, '< 3 año')])),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Produccion'), (2, 'Cobertura')])),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha aplicación')),
                ('vacuna', models.PositiveSmallIntegerField(choices=[(1, 'BCG'), (2, 'HEPATITIS'), (3, 'IPV'), (4, 'PENTA 1'), (5, 'ROTAVIRUS 1'), (6, 'NEUMO 1'), (7, 'PENTA 2'), (8, 'POLIO 2'), (9, 'ROTAVIRUS 2'), (10, 'NEUMO 2'), (11, 'POLIO 3'), (12, 'PENTA 3'), (13, 'SPR 1'), (14, 'NEUMO R1'), (15, 'SPR 2'), (16, 'DPT R1'), (17, 'POLIO R1'), (18, 'DPT R2'), (19, 'POLIO R2')])),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacunas.Comunidad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.Persona')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacunas.Personal')),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.Rango')),
            ],
        ),
    ]
