# Generated by Django 2.2.4 on 2019-09-23 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.IntegerField(default=0)),
                ('sexo', models.IntegerField(default=0)),
                ('primer_nombre', models.CharField(max_length=255)),
                ('segundo_nombre', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(max_length=255)),
                ('fecha_nac', models.DateField(verbose_name='date published')),
                ('direccion', models.CharField(max_length=255)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.Comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('cui', models.IntegerField(default=0)),
                ('renglon', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(max_length=255)),
                ('choice', models.PositiveSmallIntegerField(choices=[(1, '< 1 año'), (2, '< 2 año'), (3, '< 3 año')])),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Produccion'), (2, 'Cobertura')])),
                ('fecha', models.DateField(verbose_name='date published')),
                ('vacuna', models.PositiveSmallIntegerField(choices=[(1, 'BCG'), (2, 'HEPATITIS')])),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.Comunidad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.Persona')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.Personal')),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.Rango')),
            ],
        ),
    ]
