# Generated by Django 2.2.4 on 2019-10-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0002_auto_20190922_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')]),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='comunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacunas.Comunidad'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha aplicación'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacunas.Persona'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacunas.Personal'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='vacuna',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BCG'), (2, 'HEPATITIS'), (3, 'IPV'), (4, 'PENTA 1'), (5, 'ROTAVIRUS 1'), (6, 'NEUMO 1'), (7, 'PENTA 2'), (8, 'POLIO 2'), (9, 'ROTAVIRUS 2'), (10, 'NEUMO 2'), (11, 'POLIO 3'), (12, 'PENTA 3'), (13, 'SPR 1'), (14, 'NEUMO R1'), (15, 'SPR 2'), (16, 'DPT R1'), (17, 'POLIO R1'), (18, 'DPT R2'), (19, 'POLIO R2')]),
        ),
    ]
