# Generated by Django 2.2.4 on 2019-10-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0003_auto_20191006_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cui',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cui',
            field=models.CharField(max_length=255),
        ),
    ]
