# Generated by Django 2.2.4 on 2019-10-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0004_auto_20191006_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha aplicación'),
        ),
    ]
