# Generated by Django 2.2.4 on 2019-10-06 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0005_auto_20191006_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cui',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacunas.Comunidad'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.Persona'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacunas.Personal'),
        ),
    ]
